name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: true

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install glidertest
      run: >
        python -m pip install -r requirements-dev.txt
        && python -m pip install -e . --no-deps --force-reinstall

    - name: Full Tests
      run: |
        python -m pytest -rxs tests/
